### ISSUE TITLE
Tracking player skill (value)

### ISSUE THREAD

**Issue by elliottsmith1** [elliottsmith1/GA-RTS#1]
- ECONOMY
- [x] Total wealth
- [x] Income

- MILITARY
- [x] Total army value
- [x] Effective army value = enemy unit value loss / unit value loss

- TECHNOLOGY
- [ ] Technology value

- EXPANSION
- [x] Income capacity
- [x] Unit production capacity
- [x] Defensive capacity
- [x] Population capacity
- [x] Research capacity
